# Generated by Django 6.0.5 on 2026-05-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesis', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thesis.proposal'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supervisor'),
        ),
        migrations.AddField(
            model_name='review',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis'),
        ),
        migrations.AddField(
            model_name='defense',
            name='thesis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis'),
        ),
        migrations.AddField(
            model_name='thesisdocument',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis'),
        ),
        migrations.AddField(
            model_name='thesisgroup',
            name='thesis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesisgroup'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesisstatus'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesisstatus'),
        ),
    ]
