# Generated by Django 6.0.5 on 2026-05-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_initial'),
        ('users', '0002_alter_lecturer_department_alter_lecturer_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='proposal_documents/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
