# Generated by Django 6.0.5 on 2026-05-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_initial'),
        ('users', '0002_alter_lecturer_department_alter_lecturer_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_thesis', to='users.lecturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
