# Generated by Django 6.0.5 on 2026-05-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_thesis_supervisor_alter_groupmember_student'),
        ('users', '0002_alter_lecturer_department_alter_lecturer_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewed_by_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_reviews', to='users.lecturer'),
        ),
    ]
