# Generated by Django 6.0.5 on 2026-05-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_proposal_reviewed_at_proposal_reviewed_by_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students_per_group', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis')),
            ],
        ),
    ]
