# Generated by Django 6.0.5 on 2026-05-18 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_groupconfiguration_thesisprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='submission_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='thesis.thesisgroup'),
        ),
    ]
