# Generated by Django 6.0.5 on 2026-05-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_defense_created_at_defense_submission_deadline_and_more'),
        ('users', '0002_alter_lecturer_department_alter_lecturer_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defense',
            old_name='thesis',
            new_name='group',
        ),
        migrations.AddField(
            model_name='defense',
            name='scheduled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lecturer'),
        ),
    ]
