# Generated by Django 6.0.5 on 2026-05-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_rename_thesis_defense_group_defense_scheduled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thesis.thesisgroup'),
        ),
    ]
