# Generated by Django 6.0.5 on 2026-05-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_alter_defense_group'),
        ('users', '0002_alter_lecturer_department_alter_lecturer_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='group',
        ),
        migrations.AddField(
            model_name='defense',
            name='thesis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesis.thesis'),
        ),
        migrations.AlterField(
            model_name='defense',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lecturer'),
        ),
    ]
