# Generated by Django 6.0.5 on 2026-05-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0009_remove_defense_group_defense_thesis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group',
            new_name='gp',
        ),
    ]
