# Generated by Django 6.0.5 on 2026-05-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_rename_group_groupmember_gp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='gp',
            new_name='group',
        ),
    ]
