# Generated by Django 6.0.5 on 2026-05-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_popup_shown',
            field=models.BooleanField(default=False),
        ),
    ]
